In [1]:
import pickle as pkl

In [2]:
alphabet_list = pkl.load(open('recognize/alphabet.pkl','rb'))
alphabet = [ord(ch) for ch in alphabet_list]
alphabet_v2 = alphabet


In [8]:
print(len(alphabet_list))
print(alphabet_list)

5834
[' ', '!', '"', '#', '$', '%', '&', "'", '(', ')', '*', '+', ',', '-', '.', '/', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '=', '>', '?', '@', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '[', '\\', ']', '^', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '{', '|', '}', '~', '°', '±', '·', '×', 'à', 'é', '÷', 'ü', 'α', 'β', 'О', 'П', 'Р', '–', '—', '―', '‘', '’', '“', '”', '…', '‰', '′', '※', '℃', 'Ⅰ', 'Ⅱ', 'Ⅲ', 'Ⅳ', '→', '↓', '∈', '√', '∩', '∵', '∶', '≠', '≤', '≥', '①', '②', '③', '④', '⑤', '⑥', '⑦', '⑧', '⑨', '⑩', '⑴', '⑵', '⑶', '⑾', '⑿', '⒀', '⒂', '⒃', '⒄', '⒅', '⒆', '⒉', '─', '━', '│', '┌', '┐', '╱', '■', '□', '▲', '△', '◆', '◇', '○', '◎', '●', '★', '☆', '、', '。', '〇', '〈', '〉', '《', '》', '「', '」', '『', '』', '【', '】', '〔', '〕', 'て', 'な', '㛃', '一', '丁', '七', '万', '丈', '三', '上', '下'

In [13]:
ord(alphabet_list[199])

19981

In [20]:
print(ord("好"))
print(chr(22909))

22909
好


#### Pickle模块中最常用的函数为：
（1）pickle.dump(obj, file, [,protocol])

函数的功能：将obj对象序列化存入已经打开的file中。

参数讲解：
1）obj：想要序列化的obj对象。
2）file:文件名称。
3）protocol：序列化使用的协议。如果该项省略，则默认为0。如果为负值或HIGHEST_PROTOCOL，则使用最高的协议版本。

（2）pickle.load(file)

函数的功能：将file中的对象序列化读出。

参数讲解：
1）file：文件名称。

In [24]:
print('\t\t22\t\n33')  ## "\t" 代表横向制表符（不等于空格）， "\n" 代表换行

		22	
33


#### Python strip() 方法用于移除字符串头尾指定的字符（默认为空格）或字符序列。

功能：返回移除字符串头尾指定的字符序列生成的新字符串。

注意：该方法只能删除开头或是结尾的字符，不能删除中间部分的字符。

语法：
str.strip([chars]);

参数：
chars -- 移除字符串头尾指定的字符序列。


In [30]:
string1 = "   thomas chan	eeris"
string2 = string1.split("\t")
string2

['   thomas chan', 'eeris']

In [ ]:
# gen alphabet via label
# set() 避免重复
alphabet_set = set()
# public 公共集合，selfcollect 补充集合
infofiles = ['infofiles/infofile_selfcollect.txt','infofiles/infofile_train_public.txt']
for infofile in infofiles:
    f = open(infofile)
    content = f.readlines()  # readlines() 读取所有行，形成列表
    f.close()
    for line in content:
        if len(line.strip())>0:
            if len(line.strip().split('\t'))!=2:  # 保证一行只有两个输入， “ 文件名 + 相应的标签” 
                print(line)
            else:
                fname,label = line.strip().split('\t')   # strip()去掉起始空格，split('\t')按照横向制表符划分
                for ch in label:
                    alphabet_set.add(ch)

alphabet_list = sorted(list(alphabet_set))
pkl.dump(alphabet_list,open('alphabet.pkl','wb'))



In [32]:
import torch
torch.__version__

'1.7.1'

In [39]:
x = torch.randn(2,3)
print(x)
print(x[0][1])

tensor([[-1.1678, -1.1502,  2.6142],
        [-0.4794, -0.2851, -1.4265]])
tensor(-1.1502)


In [40]:
y = torch.randn(2,3,4)
print(y.shape)
print(y)

torch.Size([2, 3, 4])
tensor([[[-0.7966, -1.5459,  0.8427, -0.5321],
         [ 0.7184,  1.2861, -0.6432, -0.1204],
         [-1.0377,  0.0478,  0.0222,  0.3932]],

        [[ 0.2289, -0.4238, -0.5048, -0.8445],
         [ 1.7999,  0.2063,  0.5509, -0.8433],
         [-0.6352,  0.3420,  0.2486,  0.1267]]])


In [42]:
z = torch.randn(5,2,3,4)
print(z.shape)
print(z)

torch.Size([5, 2, 3, 4])
tensor([[[[ 0.9901, -0.0897,  0.8728,  0.8372],
          [ 1.1462, -1.4174, -0.9197, -0.6077],
          [ 0.8060,  0.1021,  1.1149,  0.2407]],

         [[ 0.7025, -0.3427, -0.7779, -1.1624],
          [ 0.0594, -0.1849,  1.4592, -0.7315],
          [ 2.7370,  0.6951,  0.1835, -1.4463]]],


        [[[-0.5616,  2.0016,  1.3106, -0.0085],
          [-0.4009,  0.7051,  0.8423, -0.6051],
          [-2.6678,  0.5186, -0.6823,  0.6807]],

         [[-1.1206,  1.1700, -0.9341,  0.6446],
          [-0.6745,  0.0035, -0.1328, -0.2101],
          [ 0.0510,  0.1386,  0.8772,  0.5032]]],


        [[[ 1.5436, -0.6055, -0.7546, -0.4844],
          [ 0.1974,  0.7103,  2.0429,  0.4115],
          [-1.0197, -0.7564, -1.2299,  0.5830]],

         [[-0.4014,  0.4492,  0.0399,  0.2743],
          [ 0.2679, -0.6554, -0.2782, -1.2717],
          [-0.5792,  0.0734,  2.0128,  2.5585]]],


        [[[ 0.5235, -0.5649,  1.9049,  0.2730],
          [ 0.1119,  0.6544, -0.9664, -0.9811

In [44]:
z.is_contiguous()

True

In [50]:
a = z.permute(3,0,2,1)  # a 是 z 的一个view，没有改动 z
print(a)

tensor([[[[ 0.9901,  0.7025],
          [ 1.1462,  0.0594],
          [ 0.8060,  2.7370]],

         [[-0.5616, -1.1206],
          [-0.4009, -0.6745],
          [-2.6678,  0.0510]],

         [[ 1.5436, -0.4014],
          [ 0.1974,  0.2679],
          [-1.0197, -0.5792]],

         [[ 0.5235,  0.6967],
          [ 0.1119,  0.1722],
          [ 1.0793,  0.4287]],

         [[-0.7488, -1.1026],
          [ 0.3830, -0.9599],
          [-0.2856,  1.5485]]],


        [[[-0.0897, -0.3427],
          [-1.4174, -0.1849],
          [ 0.1021,  0.6951]],

         [[ 2.0016,  1.1700],
          [ 0.7051,  0.0035],
          [ 0.5186,  0.1386]],

         [[-0.6055,  0.4492],
          [ 0.7103, -0.6554],
          [-0.7564,  0.0734]],

         [[-0.5649,  0.0297],
          [ 0.6544, -0.4742],
          [ 1.2190,  0.2360]],

         [[ 1.2360,  0.5774],
          [-1.5363,  0.9806],
          [ 0.7102,  0.0533]]],


        [[[ 0.8728, -0.7779],
          [-0.9197,  1.4592],
          [ 1.11

In [52]:
a.is_contiguous()

False

In [54]:
b = a.contiguous()
b.is_contiguous()

True

In [63]:
import numpy as np

arr1 = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
tensor1 = torch.tensor(arr1)
print(tensor1)
print(tensor1.is_contiguous())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[11, 12, 13],
         [14, 15, 16],
         [17, 18, 19]]])
True


In [69]:
tensor2 = tensor1.permute(2,0,1)
print(tensor2)
print(tensor2.shape)
print(tensor2.is_contiguous())

tensor([[[ 1,  4,  7],
         [11, 14, 17]],

        [[ 2,  5,  8],
         [12, 15, 18]],

        [[ 3,  6,  9],
         [13, 16, 19]]])
torch.Size([3, 2, 3])
False


In [65]:
tensor1.view(-1)
# 按照 NCHW->(1，2，3，3) 排列存储，然后按顺序排开

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [66]:
tensor2.view(-1)   # reason: tensor2 is not contiguous in memory

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

In [67]:
tensor3 = tensor2.contiguous()
print(tensor3)
print(tensor3.is_contiguous())
tensor3.view(-1)
# 经过 permute(2,0,1) 装置后，存储顺序为 NWCH->(1，3，2，3)
# 因此按顺序排开如下

tensor([[[ 1,  4,  7],
         [11, 14, 17]],

        [[ 2,  5,  8],
         [12, 15, 18]],

        [[ 3,  6,  9],
         [13, 16, 19]]])
True


tensor([ 1,  4,  7, 11, 14, 17,  2,  5,  8, 12, 15, 18,  3,  6,  9, 13, 16, 19])

In [71]:
tensor4 = tensor1.view(3,2,3)
print(tensor4)

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [11, 12, 13]],

        [[14, 15, 16],
         [17, 18, 19]]])


In [73]:
tensor3.view(3,2,3)

tensor([[[ 1,  4,  7],
         [11, 14, 17]],

        [[ 2,  5,  8],
         [12, 15, 18]],

        [[ 3,  6,  9],
         [13, 16, 19]]])

In [77]:
tensor5 = tensor3.reshape(3,2,3)
print(tensor5)

tensor([[[ 1,  4,  7],
         [11, 14, 17]],

        [[ 2,  5,  8],
         [12, 15, 18]],

        [[ 3,  6,  9],
         [13, 16, 19]]])


### Important conclusion:   tensor.reshape() == tensor.contiguous().view()